export const GAME_TAGS: string[] = [
  'Action',
  'Adventure',
  'RPG',
  'JRPG',
  'Racing',
  'Fighting',
  'Sports',
  'Puzzle',
  'Platformer',
  'Shooter',
  'Survival Horror',
  'Stealth',
  'Strategy',
  'Simulation',
  'Rhythm',
  "Beat 'em Up",
  'Hack and Slash',
  'Turn-Based',
  'Real-Time Strategy',
  'Tactical RPG',
  'Visual Novel',
  'Party',
  'Board Game',
  'Card Game',
  'Arcade',
  'Sandbox',
  'Open World',
  'Sci-Fi',
  'Fantasy',
  'Mecha',
  'Anime',
  'Horror',
  'Comedy',
  'Military',
  'Wrestling',
  'Boxing',
  'Soccer',
  'Baseball',
  'Basketball',
  'Golf',
  'Tennis',
  'Fishing',
  'Cooking',
  'Educational',
  'Trivia',
  'Flight Sim',
  'Space',
  'Dungeon Crawler',
  'Roguelike',
  'Metroidvania',
  'Side-Scroller',
  'Top-Down',
  'Isometric',
  'First-Person',
  'Third-Person',
  'Co-op',
  'Competitive',
  'Split-Screen',
  '2D',
  '3D',
  'Retro',
  'Classic',
  'Hidden Object',
  'Point and Click',
];
